slam_toolbox:
  ros__parameters:
    mode: mapping
    resolution: 0.05
    map_frame: map
    odom_frame: odom
    base_frame: base_link
    scan_topic: /scan
    use_odom: true
    odom_topic: /odom
    map_topic: /map
    use_map_topic: true
    publish_map_to_odom_transform: true
    publish_period_sec: 1.0   # publica mapa cada 1s
    use_sim_time: false

