slam_toolbox:
  ros__parameters:
    mode: mapping
    resolution: 0.05
    map_frame: map
    odom_frame: odom
    base_frame: base_link
    scan_topic: /scan
    use_odom: true
    odom_topic: /odom
    publish_map_to_odom_transform: true
    publish_period_sec: 1.0   # publica mapa cada 1s
    use_sim_time: false

slam_toolbox32:
  ros__parameters:
    mode: mapping
    resolution: 0.05

    # TF frames
    map_frame: map
    odom_frame: odom
    base_frame: base_link

    # Odometry
    use_odom: true
    odom_topic: /odom

    # LaserScan
    scan_topic: /scan
    max_laser_range: 5.0
    min_laser_range: 0.3

    # Colas / performance
    queue_size: 50

    # TF/map
    publish_map_to_odom_transform: true

    # Sim time
    use_sim_time: false

    publish_period_sec: 1.0
    expected_scan_count: 350

    logging_level: debug
    debug: true            # algunos builds también usan este parámetro para info extra